var kettleData = {
  "version": {
    "pointer": "10.0.1",
    "name": "vanilla"
  },
  "status": {
    "code": "200",
    "value": "success"
  },
  "data": {
    "493": {
      "queryInfo": {
        "totalRows": 5,
        "type": "selected"
      },
      "resultSet": [
        [
          "30-Apr-2015"
        ],
        [
          "26-Apr-2015"
        ],
        [
          "19-Apr-2015"
        ],
        [
          "12-Apr-2015"
        ],
        [
          "05-Apr-2015"
        ]
      ],
      "metaData": [
        {
          "colIndex": 0,
          "colType": "String",
          "colName": "Week_end"
        }
      ]
    },
    "494": {
      "queryInfo": {
        "totalRows": 22,
        "type": "selected"
      },
      "resultSet": [
        [
          "All"
        ],
        [
          "HIMATNAGAR"
        ],
        [
          "SURENDRANAGAR"
        ],
        [
          "MEHSANA"
        ],
        [
          "PALANPUR"
        ],
        [
          "GODHRA"
        ],
        [
          "JAMNAGAR"
        ],
        [
          "MEHASANA"
        ],
        [
          "AHMEDABAD"
        ],
        [
          "RAJKOT"
        ],
        [
          "BHAVNAGAR"
        ],
        [
          "AMRELI"
        ],
        [
          "BHARUCH"
        ],
        [
          "JUNAGADH"
        ],
        [
          "BHUJ"
        ],
        [
          "VADODARA"
        ],
        [
          "SURAT"
        ],
        [
          "NADIAD"
        ],
        [
          "VALSAD"
        ],
        [
          "ANAND"
        ],
        [
          "BAVLA"
        ],
        [
          "MODASA"
        ]
      ],
      "metaData": [
        {
          "colIndex": 0,
          "colType": "String",
          "colName": "District"
        }
      ]
    },
    "495": {
      "queryInfo": {
        "totalRows": 1177,
        "type": "selected"
      },
      "resultSet": [
        [
          "All"
        ],
        [
          "GODHAMJI"
        ],
        [
          "HALVAD"
        ],
        [
          "BHILODA"
        ],
        [
          "CHANDRANI"
        ],
        [
          "DHRANGDHRA"
        ],
        [
          "VITHODA"
        ],
        [
          "DEODAR"
        ],
        [
          "KUKADIYA"
        ],
        [
          "CHOTILA"
        ],
        [
          "BALDANA"
        ],
        [
          "IDAR"
        ],
        [
          "SAROLI"
        ],
        [
          "DANTA"
        ],
        [
          "ISHANPUR"
        ],
        [
          "MALPUR"
        ],
        [
          "DHANAKWADA"
        ],
        [
          "PATAN"
        ],
        [
          "SAROLI(JALETI)"
        ],
        [
          "GODHRA"
        ],
        [
          "KESHARPURA"
        ],
        [
          "HUNJ"
        ],
        [
          "SIDHPUR"
        ],
        [
          "KUNOL"
        ],
        [
          "MEGHRAJ"
        ],
        [
          "DANTIVADA"
        ],
        [
          "KELAWA"
        ],
        [
          "CHHATRALA"
        ],
        [
          "MODASA"
        ],
        [
          "DEESA"
        ],
        [
          "BIYOK"
        ],
        [
          "BHABHAR"
        ],
        [
          "UNJHA"
        ],
        [
          "NARICHANA"
        ],
        [
          "KHEDBRAHMA"
        ],
        [
          "KALOL"
        ],
        [
          "THARAD"
        ],
        [
          "LIMBDI"
        ],
        [
          "WAV"
        ],
        [
          "KHERALU"
        ],
        [
          "PALANPUR"
        ],
        [
          "SATLASANA"
        ],
        [
          "MUMANVAS"
        ],
        [
          "VIJAYNAGAR"
        ],
        [
          "KANERA"
        ],
        [
          "CHUDA"
        ],
        [
          "HIMMATNAGAR"
        ],
        [
          "VISNAGAR"
        ],
        [
          "GUNJA"
        ],
        [
          "NAVIMORVAD"
        ],
        [
          "MOTAKANTHARIA"
        ],
        [
          "KUSKI"
        ],
        [
          "WADHVAN"
        ],
        [
          "DHANERA"
        ],
        [
          "MANKADI"
        ],
        [
          "BORNA"
        ],
        [
          "ADIYA"
        ],
        [
          "SIHORI - KANKREJ"
        ],
        [
          "MOTI PIPLI"
        ],
        [
          "CHHATRIYALA"
        ],
        [
          "MAGUNA"
        ],
        [
          "THALA"
        ],
        [
          "DHUVA"
        ],
        [
          "SUDASANA"
        ],
        [
          "KUNTALPUR"
        ],
        [
          "HARIJ"
        ],
        [
          "TUNDAV"
        ],
        [
          "KANSARI"
        ],
        [
          "MANSA"
        ],
        [
          "DASADA"
        ],
        [
          "CHHABALIYA"
        ],
        [
          "SUNSAR"
        ],
        [
          "VADALI"
        ],
        [
          "GHOGHAMBA"
        ],
        [
          "VITHODAR"
        ],
        [
          "KOTADA"
        ],
        [
          "KESIMPA"
        ],
        [
          "JAKHEL"
        ],
        [
          "KANODA"
        ],
        [
          "KODARAM"
        ],
        [
          "MANKA (JUNA-NAVA)"
        ],
        [
          "VIJAPUR"
        ],
        [
          "TALOD"
        ],
        [
          "DABHODA"
        ],
        [
          "GOZARIA"
        ],
        [
          "VAYAD"
        ],
        [
          "DINDROL"
        ],
        [
          "VADNAGAR"
        ],
        [
          "DEVALIYAVALI VAV"
        ],
        [
          "PATEL DUNDA"
        ],
        [
          "RAMGADH"
        ],
        [
          "NETRAMALI"
        ],
        [
          "RADHANPUR"
        ],
        [
          "SURENDRANAGAR"
        ],
        [
          "MALOSAN"
        ],
        [
          "TETODA"
        ],
        [
          "SUREL"
        ],
        [
          "VELAVADAR"
        ],
        [
          "BECHRAJI"
        ],
        [
          "KUNWARA"
        ],
        [
          "KANT"
        ],
        [
          "BILIYA"
        ],
        [
          "RANGPUR"
        ],
        [
          "ZOBALA"
        ],
        [
          "CHANASMA"
        ],
        [
          "CHITARIYA"
        ],
        [
          "AGTHALA"
        ],
        [
          "JASAPAR"
        ],
        [
          "SANTALPUR"
        ],
        [
          "KAMBOI"
        ],
        [
          "MALEKPUR"
        ],
        [
          "KANADAR"
        ],
        [
          "GAVADA"
        ],
        [
          "SAYLA"
        ],
        [
          "MALOD"
        ],
        [
          "KALADIA"
        ],
        [
          "PATDI"
        ],
        [
          "KARLI"
        ],
        [
          "KHERALI"
        ],
        [
          "VADGAM"
        ],
        [
          "KHERAVA"
        ],
        [
          "VADOD"
        ],
        [
          "GANJELA"
        ],
        [
          "BHEMAPUR"
        ],
        [
          "DANTIWADA"
        ],
        [
          "GORAIYA"
        ],
        [
          "AMBAJI"
        ],
        [
          "DEVGADHBARIA"
        ],
        [
          "FUDEDA"
        ],
        [
          "ISRI"
        ],
        [
          "ZALMOR"
        ],
        [
          "THARA"
        ],
        [
          "PIPLOD"
        ],
        [
          "LIMKHEDA"
        ],
        [
          "DODIA"
        ],
        [
          "PREMPUR"
        ],
        [
          "SANGHPUR"
        ],
        [
          "ZABADIYA"
        ],
        [
          "LAKHTAR"
        ],
        [
          "PIPALI"
        ],
        [
          "BHACHAR"
        ],
        [
          "SANDER"
        ],
        [
          "MULOJ"
        ],
        [
          "GOLWADA"
        ],
        [
          "PRANTIJ"
        ],
        [
          "MEDH"
        ],
        [
          "NANDLA"
        ],
        [
          "BAJANA"
        ],
        [
          "VIRENDRAGADH"
        ],
        [
          "SAMI"
        ],
        [
          "SULTANPUR"
        ],
        [
          "BHETALI"
        ],
        [
          "RANSIPUR"
        ],
        [
          "MEHSANA"
        ],
        [
          "SINAWAD"
        ],
        [
          "VANIYAD"
        ],
        [
          "VASARDA"
        ],
        [
          "ANIAD"
        ],
        [
          "ENJAR"
        ],
        [
          "TIKAR"
        ],
        [
          "VEERPUR"
        ],
        [
          "VIZAPUR"
        ],
        [
          "KUDOL"
        ],
        [
          "UMBARI"
        ],
        [
          "MEVASA (MAYURNAGAR)"
        ],
        [
          "DUKHLI"
        ],
        [
          "VARAHI"
        ],
        [
          "VISAVADI"
        ],
        [
          "SAPAKADA"
        ],
        [
          "RATANPUR (KANTDI)"
        ],
        [
          "MADAL"
        ],
        [
          "SHERPURA"
        ],
        [
          "PADLA"
        ],
        [
          "DERVALA"
        ],
        [
          "CHORIWADA"
        ],
        [
          "MOTIPAVAD"
        ],
        [
          "MOTASADA"
        ],
        [
          "DENAP"
        ],
        [
          "MANEKPUR MAKAKHAD"
        ],
        [
          "VADA"
        ],
        [
          "LUDRA"
        ],
        [
          "UMARADA"
        ],
        [
          "DODGAM"
        ],
        [
          "NIMAKNAGAR"
        ],
        [
          "RANTILA"
        ],
        [
          "MORWA HADAF"
        ],
        [
          "KAMALPUR"
        ],
        [
          "BALODHAN"
        ],
        [
          "SAMOU"
        ],
        [
          "PEPALU"
        ],
        [
          "MANEKPURA"
        ],
        [
          "AMBALIYA"
        ],
        [
          "KHUSHALPUR"
        ],
        [
          "GORISANA"
        ],
        [
          "VASANA"
        ],
        [
          "JADA"
        ],
        [
          "RODA"
        ],
        [
          "SANGAL"
        ],
        [
          "DHANSURA"
        ],
        [
          "KUWARLA"
        ],
        [
          "BHADRADA"
        ],
        [
          "PADEDI"
        ],
        [
          "SOJA"
        ],
        [
          "DAHOD"
        ],
        [
          "KADI"
        ],
        [
          "MALVAN"
        ],
        [
          "AMIRGADH - IQBALGADH"
        ],
        [
          "KORDA"
        ],
        [
          "BAMANWAD"
        ],
        [
          "BAYAD"
        ],
        [
          "VAMAJ"
        ],
        [
          "MORWADA"
        ],
        [
          "MADANA (GADH)"
        ],
        [
          "FATEPURA"
        ],
        [
          "RAMPARA"
        ],
        [
          "HALOL"
        ],
        [
          "POGLU"
        ],
        [
          "SIKKA"
        ],
        [
          "JAMBUGHODA"
        ],
        [
          "HANSALPUR"
        ],
        [
          "JAGUDAN"
        ],
        [
          "JUNAUTARDA"
        ],
        [
          "BERANA"
        ],
        [
          "BASU"
        ],
        [
          "SANTRAMPUR"
        ],
        [
          "PANPUR"
        ],
        [
          "LAKHAVAD"
        ],
        [
          "LUNAWADA"
        ],
        [
          "SHEHRA"
        ],
        [
          "BHOBHA"
        ],
        [
          "LIMBODARA"
        ],
        [
          "VAGDA"
        ],
        [
          "ANTROLI"
        ],
        [
          "KADANA"
        ],
        [
          "DABHALA"
        ],
        [
          "KUVASANA"
        ],
        [
          "LUNAVADA"
        ],
        [
          "NAYTA"
        ],
        [
          "CHARADU"
        ],
        [
          "NARUKOT"
        ],
        [
          "MULI"
        ],
        [
          "NAVA"
        ],
        [
          "HATHROL"
        ],
        [
          "JAMNAGAR"
        ],
        [
          "RAJENDRANAGAR"
        ],
        [
          "TENPUR"
        ],
        [
          "VALER"
        ],
        [
          "ORAN"
        ],
        [
          "VADRAD"
        ],
        [
          "SAPAD"
        ],
        [
          "SAYRA"
        ],
        [
          "KHANPUR"
        ],
        [
          "TENIWADA"
        ],
        [
          "VATRAK"
        ],
        [
          "SIMALIYA"
        ],
        [
          "ANIOD"
        ],
        [
          "AMLAIKAMPA (BULUNDRA)"
        ],
        [
          "BAYAL DHANKROL"
        ],
        [
          "MATHASULIYA"
        ],
        [
          "HIMATNAGAR"
        ],
        [
          "DHOKALAVA(GUNDIYALA)"
        ],
        [
          "KHARA"
        ],
        [
          "AMBIKA NAGAR"
        ],
        [
          "SAKARIYA"
        ],
        [
          "DAMNODE"
        ],
        [
          "JASPUR"
        ],
        [
          "PASWADAL"
        ],
        [
          "MOTIDAU"
        ],
        [
          "RAKHIYAL"
        ],
        [
          "LIMDI"
        ],
        [
          "THANGADH"
        ],
        [
          "ANJANA"
        ],
        [
          "PALIYAD"
        ],
        [
          "PARKHADI"
        ],
        [
          "JAKASNA"
        ],
        [
          "KANSA (PART)"
        ],
        [
          "GUJARVADI"
        ],
        [
          "KHODLA"
        ],
        [
          "CHHABAU"
        ],
        [
          "BHAMAIYA"
        ],
        [
          "KUMBHALMER"
        ],
        [
          "CHEKHALA"
        ],
        [
          "DHANPUR"
        ],
        [
          "GARBADA"
        ],
        [
          "TAJPURI"
        ],
        [
          "AMBASAN"
        ],
        [
          "VEERAVADA(KARANPUR)"
        ],
        [
          "KAKAR"
        ],
        [
          "DANGIYA"
        ],
        [
          "JHALOD"
        ],
        [
          "MEHASANA"
        ],
        [
          "CHHATRAL"
        ],
        [
          "GADKAN"
        ],
        [
          "GAJAN"
        ],
        [
          "KALYANA"
        ],
        [
          "ASJOL"
        ],
        [
          "AITHOR"
        ],
        [
          "RADDODARA"
        ],
        [
          "MANIPUR"
        ],
        [
          "KANTHRAVI"
        ],
        [
          "LIMBANIVAV"
        ],
        [
          "MOJARI"
        ],
        [
          "AHMEDABAD"
        ],
        [
          "GANDHINAGAR"
        ],
        [
          "VIRAMGAM"
        ],
        [
          "DASKROI"
        ],
        [
          "DHANDHUKA"
        ],
        [
          "SANAND"
        ],
        [
          "DHOLKA"
        ],
        [
          "DEHGAM"
        ],
        [
          "DHAKDI"
        ],
        [
          "RANPUR"
        ],
        [
          "DHAR PIPLA"
        ],
        [
          "MANDAL"
        ],
        [
          "ALAMPUR"
        ],
        [
          "GHANDHINAGAR"
        ],
        [
          "BARWALA"
        ],
        [
          "MAHIJADA"
        ],
        [
          "BAVLA"
        ],
        [
          "PALUNDRA"
        ],
        [
          "ARANEJ"
        ],
        [
          "DOLARANA VASANA"
        ],
        [
          "ENASAN"
        ],
        [
          "BAGODARA"
        ],
        [
          "GALSANA"
        ],
        [
          "DHANDHUKA-2"
        ],
        [
          "CHANDRALA"
        ],
        [
          "RAIPUR"
        ],
        [
          "GANGAD"
        ],
        [
          "TAGADI"
        ],
        [
          "MORVI"
        ],
        [
          "BHAVNAGAR"
        ],
        [
          "GARIYADHAR"
        ],
        [
          "AMRELI"
        ],
        [
          "RAJKOT"
        ],
        [
          "BOTAD"
        ],
        [
          "PASAVI"
        ],
        [
          "PALITANA"
        ],
        [
          "JAM KANDORNA"
        ],
        [
          "NOGHANVADAR"
        ],
        [
          "JANGAR"
        ],
        [
          "MAHUVA"
        ],
        [
          "SHIHOR"
        ],
        [
          "TALGAJARADA"
        ],
        [
          "GHOGHA"
        ],
        [
          "KHAMBHA"
        ],
        [
          "DOLTI"
        ],
        [
          "KRANKACH"
        ],
        [
          "VIKALIYA"
        ],
        [
          "GADHADA"
        ],
        [
          "LATHI"
        ],
        [
          "MOTI KUNDAL"
        ],
        [
          "BABRA"
        ],
        [
          "MORBI"
        ],
        [
          "BAGASARA"
        ],
        [
          "TALAJA"
        ],
        [
          "JUNA NAGDAVAS"
        ],
        [
          "BHAMBAN"
        ],
        [
          "VADERA"
        ],
        [
          "DHARI"
        ],
        [
          "SHEDUBHAR"
        ],
        [
          "DEVDHARI"
        ],
        [
          "MOTA BHAMODRA"
        ],
        [
          "TORANIA"
        ],
        [
          "RAJULA"
        ],
        [
          "PAVATHI"
        ],
        [
          "AMRUTVEL"
        ],
        [
          "JETPUR"
        ],
        [
          "TATAM"
        ],
        [
          "BHAVANAGAR"
        ],
        [
          "JALALPAR"
        ],
        [
          "GONDAL"
        ],
        [
          "MANDAVDHAR"
        ],
        [
          "MOKHADAKA"
        ],
        [
          "SAVARKUNDLA"
        ],
        [
          "SALDI"
        ],
        [
          "LILIYA"
        ],
        [
          "KHORANA"
        ],
        [
          "KHIRASARA (LODHIKA)"
        ],
        [
          "NANI VAVDI"
        ],
        [
          "DHORAJI"
        ],
        [
          "VADIA"
        ],
        [
          "WANKANER"
        ],
        [
          "PIPAVAV"
        ],
        [
          "JASDAN"
        ],
        [
          "SAVAR KUNDLA"
        ],
        [
          "JAFRABAD"
        ],
        [
          "KOTHI (JASDAN)"
        ],
        [
          "UPLETA"
        ],
        [
          "ZANZMER"
        ],
        [
          "LODHIKA"
        ],
        [
          "HATHASANI"
        ],
        [
          "MALIYA"
        ],
        [
          "VIRPUR(PALITANA)"
        ],
        [
          "BHADRAWADI"
        ],
        [
          "MOTI RAJSHTHALI"
        ],
        [
          "JETPAR"
        ],
        [
          "NAIP"
        ],
        [
          "JAMBALA"
        ],
        [
          "NANA SURKA"
        ],
        [
          "SHAKPUR"
        ],
        [
          "MALAPAR"
        ],
        [
          "BHADROD"
        ],
        [
          "THADACH"
        ],
        [
          "DADVA (RANDALNA)"
        ],
        [
          "SOSIYA"
        ],
        [
          "NAVI MENGNI"
        ],
        [
          "CHALALA"
        ],
        [
          "GHUGHRALA"
        ],
        [
          "UMRALA"
        ],
        [
          "GIGASAN"
        ],
        [
          "SATHARA"
        ],
        [
          "TARED"
        ],
        [
          "MANDVA"
        ],
        [
          "GOPALGRAM"
        ],
        [
          "JIRA"
        ],
        [
          "BHADLI"
        ],
        [
          "JAM-KANDORNA"
        ],
        [
          "SURAT"
        ],
        [
          "BORDI SAMADHIYALA"
        ],
        [
          "MOTI VAVDI"
        ],
        [
          "SIDSAR"
        ],
        [
          "DERDI"
        ],
        [
          "ARAB TIMBADI"
        ],
        [
          "MAHUWA"
        ],
        [
          "DHOLIDHAR"
        ],
        [
          "MAVJINJVA"
        ],
        [
          "GADHALI"
        ],
        [
          "DEVGAM"
        ],
        [
          "BABAPUR"
        ],
        [
          "MAYAPADAR"
        ],
        [
          "HADADAD"
        ],
        [
          "DHAMEL"
        ],
        [
          "LUNI-DHAR"
        ],
        [
          "KHEVARIA"
        ],
        [
          "LUNKI"
        ],
        [
          "KHERVA"
        ],
        [
          "MEVASA"
        ],
        [
          "KOTDA SANGHANI"
        ],
        [
          "MOTA ZINZUDA"
        ],
        [
          "VALLABHIPUR"
        ],
        [
          "FULSAR"
        ],
        [
          "GHANTILA"
        ],
        [
          "MODA"
        ],
        [
          "NAVLAKHI"
        ],
        [
          "BHURKHIYA H/W"
        ],
        [
          "CHARAN SAMDHIYLA"
        ],
        [
          "KARDEJ"
        ],
        [
          "SARTANPAR"
        ],
        [
          "GOKHLANA"
        ],
        [
          "NESDI"
        ],
        [
          "LIMBADA"
        ],
        [
          "DAMNAGAR"
        ],
        [
          "GOVINDPUR"
        ],
        [
          "NAVAGAM"
        ],
        [
          "AKALA"
        ],
        [
          "PIPARDI"
        ],
        [
          "HATHAB"
        ],
        [
          "VIRPUR"
        ],
        [
          "PANELI MOTI"
        ],
        [
          "GHANGHALI"
        ],
        [
          "KHAREDA"
        ],
        [
          "CHITAL"
        ],
        [
          "PADADHARI"
        ],
        [
          "MANDILKPUR"
        ],
        [
          "GHUNTU"
        ],
        [
          "KHAJURI"
        ],
        [
          "SALPIPALIA"
        ],
        [
          "PIPALIYA DHUNDHIYA"
        ],
        [
          "MESARIA"
        ],
        [
          "VAVDI"
        ],
        [
          "KHAKHI JALIA"
        ],
        [
          "MOTI JAGDHAR"
        ],
        [
          "HAMAPUR"
        ],
        [
          "PITHADIA HW"
        ],
        [
          "THORDI"
        ],
        [
          "HAMAPAR"
        ],
        [
          "RAYDI"
        ],
        [
          "RABARIKA"
        ],
        [
          "VALSAD"
        ],
        [
          "TANKARA"
        ],
        [
          "LILAPUR"
        ],
        [
          "PANCH TALAVADA"
        ],
        [
          "HEMAL"
        ],
        [
          "NANA ANKADIYA"
        ],
        [
          "BELA"
        ],
        [
          "CHITRAVAD"
        ],
        [
          "HODATHALI"
        ],
        [
          "DATRANA"
        ],
        [
          "GANDHIDHAM"
        ],
        [
          "NAKHATRANA"
        ],
        [
          "JUNAGADH"
        ],
        [
          "BHUJ"
        ],
        [
          "DHUNVAV H/W"
        ],
        [
          "ANJAR"
        ],
        [
          "JUNAGHAD"
        ],
        [
          "LAKHPAT"
        ],
        [
          "MANAVADAR"
        ],
        [
          "ABDASA"
        ],
        [
          "KODINAR"
        ],
        [
          "KHORASA GIR"
        ],
        [
          "KALAVAD"
        ],
        [
          "VISAVADAR"
        ],
        [
          "KHAMBHALIA"
        ],
        [
          "BHACHAU"
        ],
        [
          "BHANWAD"
        ],
        [
          "MUNDRA"
        ],
        [
          "KUTIYANA"
        ],
        [
          "MALIA"
        ],
        [
          "KESHOD"
        ],
        [
          "ISHVARIYA"
        ],
        [
          "LALPUR"
        ],
        [
          "MANDVI"
        ],
        [
          "RAPAR"
        ],
        [
          "PORBANDAR"
        ],
        [
          "SANOSRA"
        ],
        [
          "VINZALPAR"
        ],
        [
          "VERAVAL"
        ],
        [
          "UNA"
        ],
        [
          "J-KALYANPUR"
        ],
        [
          "RANAVAV"
        ],
        [
          "BALACHADI"
        ],
        [
          "KALITALAVADI"
        ],
        [
          "DWARKA"
        ],
        [
          "RAMPAR®"
        ],
        [
          "DHRABAVAD"
        ],
        [
          "BHESAN"
        ],
        [
          "GARAL"
        ],
        [
          "SUTRAPADA"
        ],
        [
          "KANJHADHAR"
        ],
        [
          "MANGROL"
        ],
        [
          "VIBHAPAR"
        ],
        [
          "SAPAR TE"
        ],
        [
          "GUNDARAN"
        ],
        [
          "TALALA"
        ],
        [
          "DIU"
        ],
        [
          "SAVNI"
        ],
        [
          "JODIYA"
        ],
        [
          "HADMATIYA KHAJURI"
        ],
        [
          "MENDARDA"
        ],
        [
          "HODKA (JILL)"
        ],
        [
          "DHEBAR"
        ],
        [
          "KADIYA MOTA"
        ],
        [
          "CHANDRODA"
        ],
        [
          "DHROL"
        ],
        [
          "BAGDHARA"
        ],
        [
          "J-JODHPUR"
        ],
        [
          "DEVPAR(YAX)"
        ],
        [
          "BHANVAD"
        ],
        [
          "ANADPAR (YAX)"
        ],
        [
          "RAVAPAR"
        ],
        [
          "VANTHALI"
        ],
        [
          "KAKIDI MOLI"
        ],
        [
          "VERAD"
        ],
        [
          "LAXMIPAR"
        ],
        [
          "DHRAFA"
        ],
        [
          "KALAWAD"
        ],
        [
          "SHIVA TE"
        ],
        [
          "GADANI"
        ],
        [
          "VADAVIYALA"
        ],
        [
          "DHINCHDA"
        ],
        [
          "OKHA"
        ],
        [
          "DHAVA"
        ],
        [
          "UKADIYA"
        ],
        [
          "MOVAN"
        ],
        [
          "JAMRAVAL"
        ],
        [
          "AMBUJANAGAR"
        ],
        [
          "VIGHODI"
        ],
        [
          "SIMAR"
        ],
        [
          "AMBLASH"
        ],
        [
          "SIRAVA"
        ],
        [
          "VANANA"
        ],
        [
          "MOTIGOP"
        ],
        [
          "MOTI KHODIYAR"
        ],
        [
          "RAYDHANPAR"
        ],
        [
          "NAGHEDI"
        ],
        [
          "THEBA"
        ],
        [
          "KHIJADIYA"
        ],
        [
          "SON VADIYA"
        ],
        [
          "MANGANATH PIPLI"
        ],
        [
          "AMRAPUR GIR"
        ],
        [
          "GHUNSIYA"
        ],
        [
          "NANADIYA"
        ],
        [
          "GOREJ"
        ],
        [
          "KAMDHROL"
        ],
        [
          "KUKRAS"
        ],
        [
          "KOTDA"
        ],
        [
          "VADODARA"
        ],
        [
          "SINHADA"
        ],
        [
          "VELACHA"
        ],
        [
          "DABHOI"
        ],
        [
          "PADRA"
        ],
        [
          "OLPAD"
        ],
        [
          "VYARA"
        ],
        [
          "SACHIN"
        ],
        [
          "SAVLI"
        ],
        [
          "BARDOLI"
        ],
        [
          "NIZAR"
        ],
        [
          "CHORASI"
        ],
        [
          "KAMREJ"
        ],
        [
          "PARDI DHORAN"
        ],
        [
          "SONGADH"
        ],
        [
          "UCHHAL"
        ],
        [
          "VALOD"
        ],
        [
          "WAGHODIA"
        ],
        [
          "UCHAPAN"
        ],
        [
          "SINOR"
        ],
        [
          "CHHOTAUDEPUR"
        ],
        [
          "GUJARAT"
        ],
        [
          "PAVI-JETPUR"
        ],
        [
          "DHARAMPURI"
        ],
        [
          "BHANIYARA"
        ],
        [
          "PALSANA"
        ],
        [
          "CHHOTA UDEPUR"
        ],
        [
          "KHOLVAD"
        ],
        [
          "VAD"
        ],
        [
          "AVAKHAL"
        ],
        [
          "DEVALIA CHOKDI"
        ],
        [
          "NANPURA"
        ],
        [
          "SANKHEDA"
        ],
        [
          "ANUMALA"
        ],
        [
          "UMBHEL"
        ],
        [
          "MAHUVA SUGAR"
        ],
        [
          "GOTHADA"
        ],
        [
          "KAKRAPAR"
        ],
        [
          "NASWADI"
        ],
        [
          "KANDARI"
        ],
        [
          "NADIAD"
        ],
        [
          "ANAND"
        ],
        [
          "DHAVLI DOD"
        ],
        [
          "NAVSARI"
        ],
        [
          "NARSANDA"
        ],
        [
          "BHARUCH"
        ],
        [
          "ANKLESHWER"
        ],
        [
          "KARAMSAD"
        ],
        [
          "BHUMEL"
        ],
        [
          "KAVITHA"
        ],
        [
          "DADRA & NH"
        ],
        [
          "PARDI"
        ],
        [
          "HANSOT"
        ],
        [
          "KAPADWANJ"
        ],
        [
          "KATHALWADA"
        ],
        [
          "RAJPIPLA"
        ],
        [
          "JALALPORE"
        ],
        [
          "VANODA"
        ],
        [
          "DEDIAPADA"
        ],
        [
          "KATHLAL"
        ],
        [
          "PADGOL"
        ],
        [
          "VALIA"
        ],
        [
          "DANGS"
        ],
        [
          "GOVALI"
        ],
        [
          "PETLAD"
        ],
        [
          "SUBIR"
        ],
        [
          "BANSDA"
        ],
        [
          "MATAR"
        ],
        [
          "VAPI"
        ],
        [
          "UMBERGAM"
        ],
        [
          "LAMBHVEL"
        ],
        [
          "SELVASA"
        ],
        [
          "THASRA"
        ],
        [
          "KHEDA"
        ],
        [
          "BALASINOR"
        ],
        [
          "JAMBUSAR"
        ],
        [
          "CHAPALDHARA"
        ],
        [
          "JHAGADIA"
        ],
        [
          "SILVASSA"
        ],
        [
          "CHIKHLI"
        ],
        [
          "BHADAM"
        ],
        [
          "MAROLI CROSS ROAD"
        ],
        [
          "MAHUDHA"
        ],
        [
          "GANDEVI"
        ],
        [
          "ANKLESHWAR"
        ],
        [
          "DAMAN"
        ],
        [
          "AMOD"
        ],
        [
          "VAGRA"
        ],
        [
          "BORSAD"
        ],
        [
          "VATARIA"
        ],
        [
          "TARAPUR"
        ],
        [
          "UTTARSANDA"
        ],
        [
          "MEHMDABAD"
        ],
        [
          "KUNI"
        ],
        [
          "UMRETH"
        ],
        [
          "DAKOR"
        ],
        [
          "ANKLAV"
        ],
        [
          "SODGAM"
        ],
        [
          "LINGDA"
        ],
        [
          "DHAKWADA"
        ],
        [
          "KILLAPARDI"
        ],
        [
          "NANISINGLOTI"
        ],
        [
          "DHARAMPUR"
        ],
        [
          "HARIYA"
        ],
        [
          "KURCHAN"
        ],
        [
          "SILVASA"
        ],
        [
          "VANZANA"
        ],
        [
          "KHAMBHAT"
        ],
        [
          "DHARIKHEDA"
        ],
        [
          "VORASAMNI"
        ],
        [
          "DUNGARI"
        ],
        [
          "CAMBAY"
        ],
        [
          "SOJITRA"
        ],
        [
          "VANSDA"
        ],
        [
          "KHARETA (MOVI)"
        ],
        [
          "BHINAR"
        ],
        [
          "KHADKALA"
        ],
        [
          "MANKWA"
        ],
        [
          "ANCHELI"
        ],
        [
          "CHIKHODRA"
        ],
        [
          "ARDI"
        ],
        [
          "KHAROD"
        ],
        [
          "KANIJ"
        ],
        [
          "BAKROL"
        ],
        [
          "GANGPUR"
        ],
        [
          "HADGOOD"
        ],
        [
          "DAHISAR"
        ],
        [
          "BHATBARVAS"
        ],
        [
          "ALWADA"
        ],
        [
          "VAGDOD"
        ],
        [
          "SANTHAL"
        ],
        [
          "MANKNAJ"
        ],
        [
          "BHOYAN MOTI"
        ],
        [
          "CHAMARDI"
        ],
        [
          "GADHULI"
        ],
        [
          "KHIRASARA"
        ],
        [
          "VASSETA(GNAQ GGS)"
        ],
        [
          "CTF ANKLESHWAR"
        ],
        [
          "CTF GANDHAR 100M"
        ],
        [
          "LALI"
        ],
        [
          "VADOL"
        ],
        [
          "SALUN TALPAD"
        ],
        [
          "FAGVEL"
        ],
        [
          "BEDWA"
        ],
        [
          "PAHAJ"
        ],
        [
          "SIHUNJ"
        ],
        [
          "ALIPORE DAIRY"
        ],
        [
          "MAHUDA"
        ],
        [
          "SAGBARA"
        ],
        [
          "AVIDHA"
        ],
        [
          "VV NAGAR"
        ],
        [
          "GANDHU"
        ],
        [
          "VASAD"
        ],
        [
          "OBHA"
        ],
        [
          "VASNA GIDC"
        ],
        [
          "AHIMA"
        ],
        [
          "ASHPUR LAT"
        ],
        [
          "DABHEL"
        ],
        [
          "KUMBHARVADI"
        ],
        [
          "BANDHNI"
        ],
        [
          "RUNDEL (NEAR BOCHASAN)"
        ],
        [
          "MITRAL"
        ],
        [
          "VAREDIA"
        ],
        [
          "KANIYEL"
        ],
        [
          "SAKVA (THAVA)"
        ],
        [
          "SUNEVKALLA"
        ],
        [
          "SIHOL"
        ],
        [
          "PIPALIA"
        ],
        [
          "SANDESAR"
        ],
        [
          "PAMOL"
        ],
        [
          "AMLETHA"
        ],
        [
          "VDECHHA"
        ],
        [
          "JUJVA TEEN RASTA"
        ],
        [
          "PARIEJ"
        ],
        [
          "JITALI"
        ],
        [
          "NARANPURA LAT"
        ],
        [
          "MORAI"
        ],
        [
          "MEHMEDABAD"
        ],
        [
          "CHETARSUMBA"
        ],
        [
          "NARANPOR -PITHA"
        ],
        [
          "GARUDESHWAR"
        ],
        [
          "NADA GGS"
        ],
        [
          "UMARGAM"
        ],
        [
          "BHADBHUT"
        ],
        [
          "DEBHARI"
        ],
        [
          "VADADALA"
        ],
        [
          "CHAKLASI"
        ],
        [
          "VANKAL CHOWKADI"
        ],
        [
          "MAHISA"
        ],
        [
          "TANKARI"
        ],
        [
          "SISWA"
        ],
        [
          "BAMANVA"
        ],
        [
          "CHANVAI"
        ],
        [
          "BADARPUR"
        ],
        [
          "ACHHAWANI"
        ],
        [
          "PANDOLI"
        ],
        [
          "UMLAV"
        ],
        [
          "ASAMLI"
        ],
        [
          "JAROLA"
        ],
        [
          "KAPRADA"
        ],
        [
          "PIPLATA"
        ],
        [
          "CHUNEL"
        ],
        [
          "KANJODA"
        ],
        [
          "KHANKUVA"
        ],
        [
          "MANDIR"
        ],
        [
          "KOLAVANA"
        ],
        [
          "BHAMADIA"
        ],
        [
          "PALI"
        ],
        [
          "DHAMAN (SARAI)"
        ],
        [
          "AJARPURA"
        ],
        [
          "DABHOU (VIRSADPURA)"
        ],
        [
          "KAGVI"
        ],
        [
          "BHALADA"
        ],
        [
          "RATANPUR"
        ],
        [
          "MAGANPURA LAT"
        ],
        [
          "VADAD"
        ],
        [
          "SUNDALPURA"
        ],
        [
          "KASOR"
        ],
        [
          "BIGRI"
        ],
        [
          "NANIBEDVAN"
        ],
        [
          "NAVLI"
        ],
        [
          "KHADOL (HALDARI)"
        ],
        [
          "NAROLI"
        ],
        [
          "RUDAN"
        ],
        [
          "KADAMPURALAT"
        ],
        [
          "VAGHAS"
        ],
        [
          "SODPUR"
        ],
        [
          "DEDARDA"
        ],
        [
          "UBER"
        ],
        [
          "SURASAMAL"
        ],
        [
          "UMARWADA"
        ],
        [
          "VALVOD"
        ],
        [
          "KUNJRAO"
        ],
        [
          "VASAN"
        ],
        [
          "DEVKI VANSOL"
        ],
        [
          "TUNDEL"
        ],
        [
          "MOBHA"
        ],
        [
          "GODTHAL"
        ],
        [
          "BALA"
        ],
        [
          "JANALI"
        ],
        [
          "GOROL"
        ],
        [
          "DUDHAWA"
        ],
        [
          "KALIAKOTA"
        ],
        [
          "VERABAR (CHAPAD)"
        ],
        [
          "SIYA"
        ],
        [
          "DUVA"
        ],
        [
          "BHARADVA"
        ],
        [
          "VEDRAMPUR"
        ],
        [
          "JASKA"
        ],
        [
          "BELIYA"
        ],
        [
          "KHODA"
        ],
        [
          "KAMLI"
        ],
        [
          "MALOTRA"
        ],
        [
          "SARAL"
        ],
        [
          "RALOL"
        ],
        [
          "GHANTUDHANPURA"
        ],
        [
          "PANCHAL"
        ],
        [
          "RAVOL"
        ],
        [
          "BHOROL"
        ],
        [
          "PUNDHARA"
        ],
        [
          "GOGAMBA"
        ],
        [
          "DADHALIYA"
        ],
        [
          "BHACHALVA"
        ],
        [
          "VAMAIYA"
        ],
        [
          "JUNABARIA"
        ],
        [
          "RANJITNAGAR"
        ],
        [
          "DEV KAPDI"
        ],
        [
          "CHIBHADA"
        ],
        [
          "RIDROL"
        ],
        [
          "MEMDAVAD"
        ],
        [
          "PANSINA"
        ],
        [
          "GUNDARI"
        ],
        [
          "LOLADA"
        ],
        [
          "LAVANA(K)"
        ],
        [
          "DUDKHA"
        ],
        [
          "HARNAHODA"
        ],
        [
          "SUTHARNESADI"
        ],
        [
          "KATOSAN"
        ],
        [
          "MUJPUR"
        ],
        [
          "PANCHASAR"
        ],
        [
          "MANDAV"
        ],
        [
          "ANTELA"
        ],
        [
          "NINAMA KHAKARIA"
        ],
        [
          "DELMAL"
        ],
        [
          "BHORADU"
        ],
        [
          "DEVALIYA"
        ],
        [
          "GOTARKA"
        ],
        [
          "MELOJ"
        ],
        [
          "GHANSHYAMPUR"
        ],
        [
          "MUDETHA"
        ],
        [
          "PECHHADAL"
        ],
        [
          "BANDIBAR"
        ],
        [
          "KARAZA"
        ],
        [
          "CHHAVAD"
        ],
        [
          "MADHAV KAMPA"
        ],
        [
          "BORIAVI"
        ],
        [
          "BHATHWADA (ASAYADI)"
        ],
        [
          "TANDA"
        ],
        [
          "BHUDASAN"
        ],
        [
          "NAGHRALA"
        ],
        [
          "NANDARVA"
        ],
        [
          "KEVADIYA"
        ],
        [
          "BHAGAL"
        ],
        [
          "DARAN"
        ],
        [
          "AMBA"
        ],
        [
          "GUNELI"
        ],
        [
          "MAMADPUR"
        ],
        [
          "DAHOD,22.83022222"
        ],
        [
          "KATHLA"
        ],
        [
          "RANDIKPUR"
        ],
        [
          "MANDOR"
        ],
        [
          "BHALGAM"
        ],
        [
          "DEROLI"
        ],
        [
          "AMBALI"
        ],
        [
          "KANESAR"
        ],
        [
          "INDRAN"
        ],
        [
          "DHABDA"
        ],
        [
          "LADVEL"
        ],
        [
          "KUMBHASAN"
        ],
        [
          "NIKODA"
        ],
        [
          "UKHRELI"
        ],
        [
          "ABHLOD"
        ],
        [
          "BHE"
        ],
        [
          "VADASMA"
        ],
        [
          "LIMBDI ST STAND"
        ],
        [
          "BORAI BOCHARIA"
        ],
        [
          "VADU"
        ],
        [
          "FATEJINA GORADA"
        ],
        [
          "JORNANG"
        ],
        [
          "MOTI KANTDI"
        ],
        [
          "MAKTUPUR"
        ],
        [
          "DHGANDHRA"
        ],
        [
          "DHAMASNA"
        ],
        [
          "DIGSAR"
        ],
        [
          "VEJALPUR"
        ],
        [
          "PADRADI"
        ],
        [
          "DEROL"
        ],
        [
          "DHUDHIYA"
        ],
        [
          "BORISANA"
        ],
        [
          "SADAKPUR"
        ],
        [
          "MALAV"
        ],
        [
          "VANKDI"
        ],
        [
          "BALAYA"
        ],
        [
          "SURAJ"
        ],
        [
          "BORDI KHURD"
        ],
        [
          "HELODAR"
        ],
        [
          "KANJARI"
        ],
        [
          "DASLA"
        ],
        [
          "GARADU"
        ],
        [
          "AMODARA"
        ],
        [
          "ADOL PADEDI"
        ],
        [
          "KADWAL"
        ],
        [
          "LIMPUR"
        ],
        [
          "MAJADAR"
        ],
        [
          "BHANDOI"
        ],
        [
          "BORKHEDA"
        ],
        [
          "VASNA IYAVA"
        ],
        [
          "MOTI PAVTHI"
        ],
        [
          "BARVALA"
        ],
        [
          "PAT NA KUVA"
        ],
        [
          "GODHAVI"
        ],
        [
          "MAGODI"
        ],
        [
          "VANCH"
        ],
        [
          "KARKATHAL"
        ],
        [
          "VANPARDI"
        ],
        [
          "VANI"
        ],
        [
          "BHAVDA"
        ],
        [
          "GATRAD"
        ],
        [
          "GHAMIJ"
        ],
        [
          "GIRAMTHA"
        ],
        [
          "KASINDARA"
        ],
        [
          "RIBDI"
        ],
        [
          "VINZOL"
        ],
        [
          "DETROJ"
        ],
        [
          "SALAJADA"
        ],
        [
          "CHALODA"
        ],
        [
          "CHHARODI"
        ],
        [
          "ZOLAPUR"
        ],
        [
          "AMBLA"
        ],
        [
          "KHADSALIYA"
        ],
        [
          "PATIDAD"
        ],
        [
          "AMRAPUR"
        ],
        [
          "SARVAD"
        ],
        [
          "PANCHASIYA"
        ],
        [
          "KHIRASARA (ARNI)"
        ],
        [
          "KERIYACHAD"
        ],
        [
          "KOTDI"
        ],
        [
          "KOTHARIYA"
        ],
        [
          "JAMDADAR"
        ],
        [
          "BHVNAGAR"
        ],
        [
          "MORCHAND"
        ],
        [
          "KHADADHAR"
        ],
        [
          "PADARSHINGA"
        ],
        [
          "VANKIYA"
        ],
        [
          "BHIMDAD"
        ],
        [
          "BARVALA BAVAL"
        ],
        [
          "KALANA"
        ],
        [
          "SAKHPAR MOTA"
        ],
        [
          "RANGPAR"
        ],
        [
          "ANDARNA"
        ],
        [
          "NAGAR PIPALIA"
        ],
        [
          "BHADVA"
        ],
        [
          "UMRALI"
        ],
        [
          "MOTA CHIRODIYA"
        ],
        [
          "PIPALIYA"
        ],
        [
          "VAVANIA"
        ],
        [
          "SAMADHIYALA"
        ],
        [
          "EKLERA"
        ],
        [
          "GANOD"
        ],
        [
          "PIPALIARAJ"
        ],
        [
          "BABARIYADHAR"
        ],
        [
          "ANIDA BHALODI"
        ],
        [
          "TRAKUDA"
        ],
        [
          "THORADI"
        ],
        [
          "SARASIYA"
        ],
        [
          "MOTA HADMATIYA"
        ],
        [
          "DUMIYANI"
        ],
        [
          "JAM TIMBI"
        ],
        [
          "SATODAD"
        ],
        [
          "NAGESHRI"
        ],
        [
          "BHANDARIA"
        ],
        [
          "SEDARDA"
        ],
        [
          "PANELI"
        ],
        [
          "SAJANPAR"
        ],
        [
          "KERALA"
        ],
        [
          "KATRODI"
        ],
        [
          "SADODAR"
        ],
        [
          "SONDARDA H/W"
        ],
        [
          "MEKHDI"
        ],
        [
          "BAGDU"
        ],
        [
          "ARAMBHADA"
        ],
        [
          "VADALA"
        ],
        [
          "JAMALWADI"
        ],
        [
          "RAMANIYA"
        ],
        [
          "MODPAR"
        ],
        [
          "GOKARAN"
        ],
        [
          "BAKHARLA"
        ],
        [
          "DUDHAI"
        ],
        [
          "LAKHAPAR"
        ],
        [
          "BHOJARADO"
        ],
        [
          "HARIPUR"
        ],
        [
          "LORIYA"
        ],
        [
          "SANGNARA"
        ],
        [
          "SAMOR"
        ],
        [
          "DHUTARPAR"
        ],
        [
          "KODVAV"
        ],
        [
          "SAMTER H/W"
        ],
        [
          "SHILOJ H/W"
        ],
        [
          "ODADAR"
        ],
        [
          "SETHVADLA"
        ],
        [
          "NALIYA"
        ],
        [
          "RUDRAMATA"
        ],
        [
          "BADADIYA"
        ],
        [
          "NANA VADALA"
        ],
        [
          "MASKA"
        ],
        [
          "DESHINGA"
        ],
        [
          "MOKAR"
        ],
        [
          "RAMPAR (NETRA)"
        ],
        [
          "KATAKPARA"
        ],
        [
          "MATARVANIA"
        ],
        [
          "GINGNI"
        ],
        [
          "BHANGOR"
        ],
        [
          "LAKHABAVAL"
        ],
        [
          "KEVADRA"
        ],
        [
          "SANOSARA"
        ],
        [
          "MOTA VADALA"
        ],
        [
          "TAD"
        ],
        [
          "SAMETRA"
        ],
        [
          "DEVLI"
        ],
        [
          "MODASAR"
        ],
        [
          "BIBAR"
        ],
        [
          "ASAMBIYA MOTA"
        ],
        [
          "GAREJ"
        ],
        [
          "RAMPAR(V) TE"
        ],
        [
          "KHAMBHARA"
        ],
        [
          "NANDURI"
        ],
        [
          "JAMKALYANPUR"
        ],
        [
          "DHORI"
        ],
        [
          "ADRI"
        ],
        [
          "RAYAN"
        ],
        [
          "VARSALPAR"
        ],
        [
          "BHADIYA NANA"
        ],
        [
          "DOLASA"
        ],
        [
          "RATANPAR"
        ],
        [
          "GODHARA"
        ],
        [
          "OKHA BET"
        ],
        [
          "BITTA"
        ],
        [
          "BADA"
        ],
        [
          "RAMVAVTE"
        ],
        [
          "RANA VADVALA"
        ],
        [
          "JAMVALI"
        ],
        [
          "SATAPAR"
        ],
        [
          "VANSJALIYA"
        ],
        [
          "SAUVAI"
        ],
        [
          "KWANT"
        ],
        [
          "AFVA"
        ],
        [
          "AMBALA"
        ],
        [
          "VASEDI"
        ],
        [
          "UMARPADA"
        ],
        [
          "DHANTEJ"
        ],
        [
          "BAHURUPA"
        ],
        [
          "GHATA"
        ],
        [
          "KURALI"
        ],
        [
          "AMALGUNDI"
        ],
        [
          "BHAGUMARA"
        ],
        [
          "KOTHAMBA"
        ],
        [
          "VEDCHHI"
        ],
        [
          "TIMBA/NANSAD"
        ],
        [
          "KARALI"
        ],
        [
          "BHARUNDI"
        ],
        [
          "AMODAR VILLAGE"
        ],
        [
          "RAVAL"
        ],
        [
          "RANU"
        ],
        [
          "GUTAL"
        ],
        [
          "TILAKWADA"
        ],
        [
          "SARPANCH"
        ],
        [
          "CHHALIER"
        ],
        [
          "LAKODARA VILLAGE"
        ],
        [
          "GUNDICHA"
        ],
        [
          "BHATA"
        ],
        [
          "CHITRAL"
        ],
        [
          "ASOJ VILLAGE"
        ],
        [
          "VARNAMA"
        ],
        [
          "MANKANI"
        ],
        [
          "SAVALI"
        ],
        [
          "SAYDLA (SURALI)"
        ],
        [
          "CHANSAD"
        ],
        [
          "BHIKAPURA"
        ],
        [
          "PALASWADA"
        ],
        [
          "VADAJ CHANWADA"
        ],
        [
          "ITOALA"
        ],
        [
          "TIMBERVA"
        ],
        [
          "KHEDA KARMASIYA"
        ],
        [
          "VANESA PISAD"
        ],
        [
          "SATHOD"
        ],
        [
          "MANDALA"
        ],
        [
          "MEVALI"
        ],
        [
          "KURAL"
        ],
        [
          "VADODARA (RURAL)"
        ],
        [
          "DAMKA"
        ],
        [
          "KOLIYAD VILLAGE"
        ],
        [
          "GANGAPUR"
        ],
        [
          "MANDAVKHADAK"
        ],
        [
          "TUWA"
        ],
        [
          "GAMBHU"
        ],
        [
          "DHANDHALPUR"
        ],
        [
          "DEMTI"
        ],
        [
          "NOLI"
        ],
        [
          "HADALA"
        ],
        [
          "VELPURA"
        ],
        [
          "KHOJALVASA"
        ],
        [
          "KANZ"
        ],
        [
          "DANGARVA"
        ],
        [
          "SUNDARIYANA"
        ],
        [
          "KARIYANA"
        ],
        [
          "PIPARTODA"
        ],
        [
          "VASAI H/W"
        ],
        [
          "INDUSTRIAL AREA"
        ],
        [
          "MANJROL"
        ],
        [
          "BHAYAPURA"
        ],
        [
          "MORTHAL"
        ],
        [
          "MIRAP"
        ],
        [
          "KUKARDA"
        ],
        [
          "HARMADIYA"
        ],
        [
          "KHUDAD"
        ],
        [
          "HARIGANESH SOC"
        ],
        [
          "PUSHPAK COMPLEX"
        ],
        [
          "KHOHRA"
        ],
        [
          "SATYAMCOLONY"
        ],
        [
          "BILL"
        ],
        [
          "SAHIJ"
        ],
        [
          "RANODRA"
        ],
        [
          "CHOKARI"
        ],
        [
          "SARANGPUR"
        ],
        [
          "ALAU"
        ],
        [
          "HIMALAYAMALL"
        ],
        [
          "AMBAPUR"
        ],
        [
          "NILKANTH ARCADE"
        ],
        [
          "SOLAPARASNAGAR"
        ],
        [
          "PETHAPUR"
        ],
        [
          "KARBATIYA"
        ],
        [
          "DABHELA"
        ],
        [
          "BHAVANICHAMBER"
        ],
        [
          "NAVAGAMGHED"
        ],
        [
          "DABHOLIVILLAGE"
        ],
        [
          "PATAL"
        ],
        [
          "GREENACREPRAHLAD"
        ],
        [
          "CHIKHLA"
        ],
        [
          "SANDHIYER"
        ],
        [
          "ISCON MALL"
        ]
      ],
      "metaData": [
        {
          "colIndex": 0,
          "colType": "String",
          "colName": "City"
        }
      ]
    },
    "501": {
      "queryInfo": {
        "totalRows": 92,
        "type": "selected"
      },
      "resultSet": [
        [
          "All"
        ],
        [
          "HIMMATNGR04"
        ],
        [
          "SURENDRANAGAR01"
        ],
        [
          "MEHASANA01"
        ],
        [
          "PALANPUR02"
        ],
        [
          "SURENDRANAGAR02"
        ],
        [
          "SURENDRANAGAR03"
        ],
        [
          "HIMMATNGR02"
        ],
        [
          "HIMMATNGR03"
        ],
        [
          "PALANPUR03"
        ],
        [
          "HIMMATNGR01"
        ],
        [
          "MEHASANA03"
        ],
        [
          "GODHRA01"
        ],
        [
          "DEESA01"
        ],
        [
          "PALANPUR01"
        ],
        [
          "MEHASANA02"
        ],
        [
          "MEHASANA04"
        ],
        [
          "GODHRA04"
        ],
        [
          "MEH05"
        ],
        [
          "SURENDRANAGAR04"
        ],
        [
          "HMTT05"
        ],
        [
          "PNP05"
        ],
        [
          "MEH06"
        ],
        [
          "HMT06"
        ],
        [
          "GODHRA05"
        ],
        [
          "BSS:16"
        ],
        [
          "DAHOD01"
        ],
        [
          "SHAHI07"
        ],
        [
          "SHAHI06"
        ],
        [
          "SHAHIBAUGH03"
        ],
        [
          "GJ_BSC_208_ZTE_AHM2(208)"
        ],
        [
          "VASTRAPUR03"
        ],
        [
          "GJ_BSC_207_ZTE_AHM1(207)"
        ],
        [
          "BAPUNGR01"
        ],
        [
          "VASTRAPUR04"
        ],
        [
          "VASTRAPUR02"
        ],
        [
          "SHAHIBAUGH02"
        ],
        [
          "VAST06"
        ],
        [
          "VASTRAPUR01"
        ],
        [
          "SHAHIBAUGH04"
        ],
        [
          "SHAHIBAUGH01"
        ],
        [
          "RAJKOT07"
        ],
        [
          "BHVNAGAR05"
        ],
        [
          "BHVNAGAR03"
        ],
        [
          "AMRELI03"
        ],
        [
          "BHVNAGAR02"
        ],
        [
          "GJ_BSC_209_ZTE_RKT1(209)"
        ],
        [
          "RAJKOT05"
        ],
        [
          "RAJKOT04"
        ],
        [
          "BHVNAGAR04"
        ],
        [
          "RAJKOT03"
        ],
        [
          "AMRELI02"
        ],
        [
          "AMRELI01"
        ],
        [
          "BHVNAGAR01"
        ],
        [
          "RAJKOT06"
        ],
        [
          "JNDGADH06"
        ],
        [
          "BHUJ05"
        ],
        [
          "JAMNAGAR03"
        ],
        [
          "BHUJ02"
        ],
        [
          "BHUJ06"
        ],
        [
          "BHUJ01"
        ],
        [
          "JNDGADH05"
        ],
        [
          "JNDGADH03"
        ],
        [
          "JNDGADH02"
        ],
        [
          "JAMNAGAR01"
        ],
        [
          "JAMNAGAR04"
        ],
        [
          "JNDGADH01"
        ],
        [
          "BHUJ04"
        ],
        [
          "VADODARA05"
        ],
        [
          "VADODARA06"
        ],
        [
          "SURAT07"
        ],
        [
          "SURAT08"
        ],
        [
          "SURAT06"
        ],
        [
          "VADODARA03"
        ],
        [
          "SURAT05"
        ],
        [
          "VADODARA02"
        ],
        [
          "SURAT04"
        ],
        [
          "VADODARA04"
        ],
        [
          "BARDOLI01"
        ],
        [
          "NADIAD05"
        ],
        [
          "NADIAD04"
        ],
        [
          "VALSAD05"
        ],
        [
          "VALSAD04"
        ],
        [
          "BHARUCH05"
        ],
        [
          "BHARUCH01"
        ],
        [
          "NADIAD01"
        ],
        [
          "BHARUCH03"
        ],
        [
          "VALSAD02"
        ],
        [
          "BHARUCH02"
        ],
        [
          "NADIAD02"
        ],
        [
          "BHARUCH04"
        ],
        [
          "VALSAD01"
        ]
      ],
      "metaData": [
        {
          "colIndex": 0,
          "colType": "String",
          "colName": "BCF Name"
        }
      ]
    },
    "502": {
      "queryInfo": {
        "totalRows": 141,
        "type": "selected"
      },
      "resultSet": [
        [
          "All"
        ],
        [
          "6325"
        ],
        [
          "6322"
        ],
        [
          "6315"
        ],
        [
          "6314"
        ],
        [
          "6313"
        ],
        [
          "6312"
        ],
        [
          "6311"
        ],
        [
          "6244"
        ],
        [
          "6235"
        ],
        [
          "6234"
        ],
        [
          "6225"
        ],
        [
          "6224"
        ],
        [
          "6222"
        ],
        [
          "6215"
        ],
        [
          "6214"
        ],
        [
          "6212"
        ],
        [
          "6211"
        ],
        [
          "5924"
        ],
        [
          "5915"
        ],
        [
          "5914"
        ],
        [
          "5913"
        ],
        [
          "5911"
        ],
        [
          "5714"
        ],
        [
          "5713"
        ],
        [
          "5712"
        ],
        [
          "5711"
        ],
        [
          "5435"
        ],
        [
          "5426"
        ],
        [
          "5425"
        ],
        [
          "5424"
        ],
        [
          "5423"
        ],
        [
          "5416"
        ],
        [
          "5415"
        ],
        [
          "5414"
        ],
        [
          "5413"
        ],
        [
          "5412"
        ],
        [
          "5411"
        ],
        [
          "5326"
        ],
        [
          "5316"
        ],
        [
          "5315"
        ],
        [
          "5313"
        ],
        [
          "5312"
        ],
        [
          "5311"
        ],
        [
          "4826"
        ],
        [
          "4825"
        ],
        [
          "4824"
        ],
        [
          "4816"
        ],
        [
          "4815"
        ],
        [
          "4814"
        ],
        [
          "4812"
        ],
        [
          "4811"
        ],
        [
          "4423"
        ],
        [
          "4413"
        ],
        [
          "4412"
        ],
        [
          "4411"
        ],
        [
          "4355"
        ],
        [
          "4345"
        ],
        [
          "4335"
        ],
        [
          "4325"
        ],
        [
          "4323"
        ],
        [
          "4321"
        ],
        [
          "4315"
        ],
        [
          "4314"
        ],
        [
          "4313"
        ],
        [
          "4312"
        ],
        [
          "4311"
        ],
        [
          "4223"
        ],
        [
          "4214"
        ],
        [
          "4213"
        ],
        [
          "4211"
        ],
        [
          "42"
        ],
        [
          "4082"
        ],
        [
          "4081"
        ],
        [
          "4047"
        ],
        [
          "4037"
        ],
        [
          "4036"
        ],
        [
          "4027"
        ],
        [
          "4026"
        ],
        [
          "4017"
        ],
        [
          "4016"
        ],
        [
          "4015"
        ],
        [
          "4014"
        ],
        [
          "4013"
        ],
        [
          "3825"
        ],
        [
          "3822"
        ],
        [
          "3815"
        ],
        [
          "3814"
        ],
        [
          "3813"
        ],
        [
          "3812"
        ],
        [
          "3811"
        ],
        [
          "3026"
        ],
        [
          "3025"
        ],
        [
          "3016"
        ],
        [
          "3015"
        ],
        [
          "3014"
        ],
        [
          "3013"
        ],
        [
          "3012"
        ],
        [
          "2322"
        ],
        [
          "2028"
        ],
        [
          "2027"
        ],
        [
          "2026"
        ],
        [
          "2019"
        ],
        [
          "2018"
        ],
        [
          "2017"
        ],
        [
          "2016"
        ],
        [
          "2015"
        ],
        [
          "2014"
        ],
        [
          "1826"
        ],
        [
          "1823"
        ],
        [
          "1816"
        ],
        [
          "1815"
        ],
        [
          "1814"
        ],
        [
          "1813"
        ],
        [
          "1812"
        ],
        [
          "1811"
        ],
        [
          "1634"
        ],
        [
          "1625"
        ],
        [
          "1624"
        ],
        [
          "1615"
        ],
        [
          "1614"
        ],
        [
          "1612"
        ],
        [
          "1611"
        ],
        [
          "1086"
        ],
        [
          "1085"
        ],
        [
          "1081"
        ],
        [
          "1056"
        ],
        [
          "1037"
        ],
        [
          "1036"
        ],
        [
          "1027"
        ],
        [
          "1026"
        ],
        [
          "1025"
        ],
        [
          "1024"
        ],
        [
          "1023"
        ],
        [
          "1022"
        ],
        [
          "1021"
        ],
        [
          "1016"
        ],
        [
          "1014"
        ],
        [
          "1013"
        ],
        [
          "1012"
        ],
        [
          "1011"
        ]
      ],
      "metaData": [
        {
          "colIndex": 0,
          "colType": "String",
          "colName": "Location ID"
        }
      ]
    },
    "503": {
      "queryInfo": {
        "totalRows": 26,
        "type": "selected"
      },
      "resultSet": [
        [
          "All"
        ],
        [
          "AMD001_ASLALI"
        ],
        [
          "AMD003_BAPUNAGAR"
        ],
        [
          "AMD004_BAPUNAGARHUDCO"
        ],
        [
          "AMD005_BHADRATE"
        ],
        [
          "AMD006_BHARVITOWER"
        ],
        [
          "AMD009_CAMAPLOT"
        ],
        [
          "AMD010_CHAMUNDA"
        ],
        [
          "AMD011_DHORBAZARTE"
        ],
        [
          "AMD012_GANJBAZAR"
        ],
        [
          "AMD014_GOPIAVENUE"
        ],
        [
          "AMD017_ISANPURSCHL"
        ],
        [
          "AMD019_JAMALPUR"
        ],
        [
          "AMD023_KRISHNATOWER"
        ],
        [
          "AMD026_NAGORI"
        ],
        [
          "AMD028_NARODA"
        ],
        [
          "AMD029_NAROLSCHOOL"
        ],
        [
          "AMD034_ODHAVTE"
        ],
        [
          "AMD035_PARTHEMPIRE"
        ],
        [
          "AMD036_RAILWAYPURA"
        ],
        [
          "AMD037_RAJPURSCHOOL"
        ],
        [
          "AMD041_SAMPATITWR"
        ],
        [
          "AMD042_SEWAGEPUMP"
        ],
        [
          "AMD043_SHAHIBAUG"
        ],
        [
          "AMD044_SHAHIBAUGRTSD"
        ],
        [
          "AMD045_SUKHRAMNAGAR"
        ]
      ],
      "metaData": [
        {
          "colIndex": 0,
          "colType": "String",
          "colName": "BTS Name"
        }
      ]
    },
    "504": {
      "queryInfo": {
        "totalRows": 4,
        "type": "selected"
      },
      "resultSet": [
        [
          "All"
        ],
        [
          "Off-Net"
        ],
        [
          "On-Net"
        ],
        [
          "ISD"
        ]
      ],
      "metaData": [
        {
          "colIndex": 0,
          "colType": "String",
          "colName": "Call Category"
        }
      ]
    },
    "505": {
      "queryInfo": {
        "totalRows": 24,
        "type": "selected"
      },
      "resultSet": [
        [
          "All"
        ],
        [
          "Gujarat"
        ],
        [
          "Rajasthan"
        ],
        [
          "Madhya Pradesh"
        ],
        [
          "Bihar"
        ],
        [
          "Haryana"
        ],
        [
          "Orissa"
        ],
        [
          "Mumbai"
        ],
        [
          "Uttar Pradesh (East)"
        ],
        [
          "Maharashtra"
        ],
        [
          "Delhi"
        ],
        [
          "Uttar Pradesh (West)"
        ],
        [
          "Kolkata"
        ],
        [
          "Himachal Pradesh"
        ],
        [
          "Punjab"
        ],
        [
          "Karnataka"
        ],
        [
          "Andhra Pradesh"
        ],
        [
          "Assam "
        ],
        [
          "West Bengal"
        ],
        [
          "Tamilnadu (excluding Chennai)"
        ],
        [
          "Jammu & Kashmir"
        ],
        [
          "Kerala"
        ],
        [
          "Chennai"
        ],
        [
          "North East"
        ]
      ],
      "metaData": [
        {
          "colIndex": 0,
          "colType": "String",
          "colName": "Called Region"
        }
      ]
    },
    "506": {
      "queryInfo": {
        "totalRows": 3,
        "type": "selected"
      },
      "resultSet": [
        [
          "All"
        ],
        [
          "Night Time"
        ],
        [
          "Day Time"
        ]
      ],
      "metaData": [
        {
          "colIndex": 0,
          "colType": "String",
          "colName": "Time Of Day"
        }
      ]
    },
    "507": {
      "queryInfo": {
        "totalRows": 4,
        "type": "selected"
      },
      "resultSet": [
        [
          "COC"
        ],
        [
          "DAT"
        ],
        [
          "MOC"
        ],
        [
          "PPD"
        ]
      ],
      "metaData": [
        {
          "colIndex": 0,
          "colType": "String",
          "colName": "Call Type"
        }
      ]
    },
    "513": {
      "queryInfo": {
        "totalRows": 1,
        "type": "selected"
      },
      "resultSet": [
        [
          "1489.3287"
        ]
      ],
      "metaData": [
        {
          "colIndex": 0,
          "colType": "BigNumber",
          "colName": "Total Usage"
        }
      ]
    },
    "516": {
      "queryInfo": {
        "totalRows": 1,
        "type": "selected"
      },
      "resultSet": [
        [
          "354.18043672"
        ]
      ],
      "metaData": [
        {
          "colIndex": 0,
          "colType": "BigNumber",
          "colName": "Avg Usage"
        }
      ]
    },
    "518": {
      "queryInfo": {
        "totalRows": 1,
        "type": "selected"
      },
      "resultSet": [
        [
          "125150.3"
        ]
      ],
      "metaData": [
        {
          "colIndex": 0,
          "colType": "Number",
          "colName": "Total Revenue Units"
        }
      ]
    },
    "520": {
      "queryInfo": {
        "totalRows": 1,
        "type": "selected"
      },
      "resultSet": [
        [
          "29762.3"
        ]
      ],
      "metaData": [
        {
          "colIndex": 0,
          "colType": "Number",
          "colName": "Average Revenue Units"
        }
      ]
    },
    "526": {
      "queryInfo": {
        "totalRows": 3,
        "type": "selected"
      },
      "resultSet": [
        [
          "ISD",
          "0",
          "0",
          "320994.6"
        ],
        [
          "Local",
          "40496874.3",
          "59373596.4",
          "0"
        ],
        [
          "STD",
          "5379259",
          "19579588.2",
          "0"
        ]
      ],
      "metaData": [
        {
          "colIndex": 0,
          "colType": "String",
          "colName": "Categories"
        },
        {
          "colIndex": 1,
          "colType": "Number",
          "colName": "On-Net"
        },
        {
          "colIndex": 2,
          "colType": "Number",
          "colName": "Off-Net"
        },
        {
          "colIndex": 3,
          "colType": "Number",
          "colName": "ISD"
        }
      ]
    },
    "556": {
      "queryInfo": {
        "totalRows": 5,
        "type": "selected"
      },
      "resultSet": [
        [
          "BUJ250_ARCHEANCHEMICAL_5",
          "77016.5",
          "228413.2",
          "4072.2",
          "309501.93",
          "24.9",
          "73.8",
          "1.3"
        ],
        [
          "BCH118_KEVDIADAM",
          "59954.7",
          "210620.6",
          "25.7",
          "270600.98",
          "22.2",
          "77.8",
          "0"
        ],
        [
          "AMD043_SHAHIBAUG",
          "67051.2",
          "152789.3",
          "431.6",
          "220272.09",
          "30.4",
          "69.4",
          "0.2"
        ],
        [
          "VAL086_AHWA",
          "171649.2",
          "47702.2",
          "63.9",
          "219415.2",
          "78.2",
          "21.7",
          "0"
        ],
        [
          "VAL204_SUBIR_5",
          "171778",
          "39032.6",
          "114.3",
          "210924.9",
          "81.4",
          "18.5",
          "0.1"
        ]
      ],
      "metaData": [
        {
          "colIndex": 0,
          "colType": "String",
          "colName": "BTS"
        },
        {
          "colIndex": 1,
          "colType": "Number",
          "colName": "Local"
        },
        {
          "colIndex": 2,
          "colType": "Number",
          "colName": "STD"
        },
        {
          "colIndex": 3,
          "colType": "Number",
          "colName": "ISD"
        },
        {
          "colIndex": 4,
          "colType": "BigNumber",
          "colName": "Revenue Unit"
        },
        {
          "colIndex": 5,
          "colType": "Number",
          "colName": "Local%"
        },
        {
          "colIndex": 6,
          "colType": "Number",
          "colName": "STD%"
        },
        {
          "colIndex": 7,
          "colType": "Number",
          "colName": "ISD%"
        }
      ]
    },
    "558": {
      "queryInfo": {
        "totalRows": 5,
        "type": "selected"
      },
      "resultSet": [
        [
          "AHMEDABAD",
          "13808763.4"
        ],
        [
          "SURAT",
          "7056951.5"
        ],
        [
          "RAJKOT",
          "5677198"
        ],
        [
          "VADODARA",
          "5483510.4"
        ],
        [
          "BHUJ",
          "3431532.5"
        ]
      ],
      "metaData": [
        {
          "colIndex": 0,
          "colType": "String",
          "colName": "case when instr(city,'\"') > 0 then substr(City,3,50) else City end"
        },
        {
          "colIndex": 1,
          "colType": "Number",
          "colName": "sum(Revenue_Unit)"
        }
      ]
    },
    "560": {
      "queryInfo": {
        "totalRows": 30,
        "type": "selected"
      },
      "resultSet": [
        [
          "01-Apr-2015",
          "448",
          "375",
          "905",
          "940",
          "1456"
        ],
        [
          "02-Apr-2015",
          "499",
          "357",
          "967",
          "948",
          "1344"
        ],
        [
          "03-Apr-2015",
          "491",
          "370",
          "960",
          "924",
          "1345"
        ],
        [
          "04-Apr-2015",
          "484",
          "360",
          "1017",
          "922",
          "1332"
        ],
        [
          "05-Apr-2015",
          "519",
          "401",
          "1019",
          "940",
          "1220"
        ],
        [
          "06-Apr-2015",
          "463",
          "343",
          "937",
          "925",
          "1445"
        ],
        [
          "07-Apr-2015",
          "482",
          "346",
          "934",
          "912",
          "1444"
        ],
        [
          "08-Apr-2015",
          "482",
          "358",
          "922",
          "946",
          "1415"
        ],
        [
          "09-Apr-2015",
          "479",
          "343",
          "961",
          "922",
          "1426"
        ],
        [
          "10-Apr-2015",
          "509",
          "342",
          "969",
          "916",
          "1413"
        ],
        [
          "11-Apr-2015",
          "517",
          "378",
          "956",
          "941",
          "1357"
        ],
        [
          "12-Apr-2015",
          "549",
          "364",
          "1060",
          "908",
          "1200"
        ],
        [
          "13-Apr-2015",
          "515",
          "326",
          "939",
          "911",
          "1424"
        ],
        [
          "14-Apr-2015",
          "477",
          "377",
          "941",
          "961",
          "1355"
        ],
        [
          "15-Apr-2015",
          "503",
          "350",
          "945",
          "919",
          "1429"
        ],
        [
          "16-Apr-2015",
          "497",
          "359",
          "933",
          "935",
          "1421"
        ],
        [
          "17-Apr-2015",
          "525",
          "363",
          "933",
          "952",
          "1391"
        ],
        [
          "18-Apr-2015",
          "519",
          "364",
          "964",
          "938",
          "1374"
        ],
        [
          "19-Apr-2015",
          "538",
          "425",
          "1057",
          "933",
          "1183"
        ],
        [
          "20-Apr-2015",
          "520",
          "373",
          "967",
          "939",
          "1348"
        ],
        [
          "21-Apr-2015",
          "532",
          "370",
          "954",
          "950",
          "1310"
        ],
        [
          "22-Apr-2015",
          "485",
          "358",
          "960",
          "919",
          "1323"
        ],
        [
          "23-Apr-2015",
          "526",
          "363",
          "948",
          "943",
          "1350"
        ],
        [
          "24-Apr-2015",
          "492",
          "372",
          "966",
          "960",
          "1369"
        ],
        [
          "25-Apr-2015",
          "485",
          "362",
          "988",
          "928",
          "1402"
        ],
        [
          "26-Apr-2015",
          "559",
          "415",
          "1076",
          "988",
          "1111"
        ],
        [
          "27-Apr-2015",
          "549",
          "385",
          "995",
          "965",
          "1276"
        ],
        [
          "28-Apr-2015",
          "546",
          "390",
          "981",
          "974",
          "1283"
        ],
        [
          "29-Apr-2015",
          "547",
          "374",
          "980",
          "973",
          "1299"
        ],
        [
          "30-Apr-2015",
          "559",
          "395",
          "972",
          "970",
          "1281"
        ]
      ],
      "metaData": [
        {
          "colIndex": 0,
          "colType": "String",
          "colName": "Calling_Date"
        },
        {
          "colIndex": 1,
          "colType": "Integer",
          "colName": "Very Low"
        },
        {
          "colIndex": 2,
          "colType": "Integer",
          "colName": "Low"
        },
        {
          "colIndex": 3,
          "colType": "Integer",
          "colName": "Medium"
        },
        {
          "colIndex": 4,
          "colType": "Integer",
          "colName": "High"
        },
        {
          "colIndex": 5,
          "colType": "Integer",
          "colName": "Very High"
        }
      ]
    }
  },
  "error": false
};